import Head from "next/head";
import React, { Component } from "react";
import Navbar from "./navbar/Navbar";

class Layout extends Component {
    render() {
        return (
            <div className="layout">
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar></Navbar>
            </div>
        );
    }
}

export default Layout;
